In [1]:
import numpy as np 

arr1= np.array([1,2,3,4,5]) # passing list , !D

arr2 = arr1*5
print(arr2) # single instruction to perform an operation

#nd array 
print(type(arr1))

[ 5 10 15 20 25]
<class 'numpy.ndarray'>


In [2]:
#1d array 
arr1= np.array([1,2,3,4,5])



#2d array 
arr2=np.array([[1,2,3] ,
               [4,5,6]]) # rowand column



#3d array 
arr3 = np.array([[ [1,2,3] ,   #
                   [4,5,6] ] , 

                   [ [7,8,9] ,
                 [10,11,12] ]
                 
                 ])

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

print(arr1.shape) # row only
print(arr2.shape) # row and column
print(arr3.shape) # row and column and depth

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

print(arr1.size) 

1
2
3
(5,)
(2, 3)
(2, 2, 3)
int64
int64
int64
5


In [3]:

string_array= np.array([1,2,3,'d'])
#print(string_array)

arr= np.array([1,2,3,4,5] , dtype = np.float64) # 64 bit floating point number

print(arr.dtype)


float64


In [4]:
#dta type 
list1 = [1,2,3,4,5.6]

arr1 = np.array(list1 , dtype = np.int32) # int32 ranges from -2,147,483,648 to 2,147,483,647

print(arr1) # upcasting of 5,6 to 5  , U32 -> string 



[1 2 3 4 5]


In [5]:
# from tuple to np array 

tpl =(1,2,3,4,5)

arr= np.array(tpl)
arr= arr.astype(np.int64)
#print(arr)
#print(type(arr))
#print(arr.dtype)

# from  set to np array

set = { 1,2,3,4,5}
arr2= np.array(set)
 # converting the set into np array as object {}
print(arr2)
print(type(arr2))
print(arr2.dtype)

arr2 = np.array(list(set)) # set to list to np array 
print(arr2)
print(type(arr2))


{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>
object
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
# dictionary to np array

dc = {
    'name' : "eva"  ,  # key-value pair
    'age' : 25 ,
    'phone' : 1234567890
}

#print(dc)
keys = dc.keys()
values = dc.values()
item =dc.items()
#print(keys , values)
print(item)

arr =np.array(list(item)) #converting each items into list then to array
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)

dict_items([('name', 'eva'), ('age', 25), ('phone', 1234567890)])
[['name' 'eva']
 ['age' '25']
 ['phone' '1234567890']]
<class 'numpy.ndarray'>
<U21
(3, 2)


In [7]:
# array with random values 

arr = np.random.rand(2,4) # 2 rows and 4 columns / shape 
print(arr)
print(type(arr))
print(arr.dtype)    
print(arr.ndim)

arr2 = np.random.randint(1, 100 , size=(2,3))
#arr3= np.random.uniform(1,100,size=(2,3)) #floating numbers 
print(arr2)
print(type(arr2))
print(arr2.dtype)

[[0.2995188  0.79905335 0.58791112 0.43782427]
 [0.58357056 0.05250553 0.58324191 0.96405486]]
<class 'numpy.ndarray'>
float64
2
[[ 7 98 40]
 [46 90 31]]
<class 'numpy.ndarray'>
int32


In [8]:
# np array with range values 
# np.arange(start , stop , step)  # step is optional by default it is 1

arr=np.arange(1,20 ,2 )
print(arr)
arr2 = np.arange(0,10 , 1).reshape(2,5) # reshape the array into 2 rows and 5 columns matrix
print(arr2)

[ 1  3  5  7  9 11 13 15 17 19]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
#linear spaced array

arr= np.linspace(1,10,5) # start , stop , number of values to be generated between start and stop
print(arr) # evenly distributed


#np.logspace(start , stop , num) # num is number of values to be generated between start and stop on log scale

arr2=np.logspace(1,10,5) # 10^1 to 10^10  , 5 values 
print(arr2)

[ 1.    3.25  5.5   7.75 10.  ]
[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]


In [10]:
#indexing and slicing 

#1d array 
arr1= np.array([1,2,3,4,5])

#2d array 
arr2=np.array([[1,2,3] ,
               [4,5,6] ,
               [7,8,9],
               [10,11,12]]) # row and column

#print(arr2[1,2]) # 1 is row index and 2 is column index
arr2[0,1]=200
#print(arr2)

#slicing , id =arr[start:stop:step]
arr3  = arr1[1:4:2]
print(arr3)

# 2d array -> arr[row_start :row_stop:row_step , column_start : column_stop : column_step]
row_0=arr2[0:1, ]
#print(row_0)
col_0=arr2[ : , 0:1]
#print(col_0)
slice = arr2[1:3 , 1:3]
print(slice)

# get 5 , 9 
#print(arr2[[1,2] , [1,2]] )

print(arr2[arr2>2])

[2 4]
[[5 6]
 [8 9]]
[200   3   4   5   6   7   8   9  10  11  12]


In [11]:
#advanced indexing

arr= np.array([1,2,3,5,6])
arr2=arr[1:2].copy() # to avoid the reference of arr2 to arr
arr2=100
print(arr)

[1 2 3 5 6]


In [12]:
#iteration 
arr=[[1,2,3] ,
     [4,5,6] ]

for i in  np.nditer(arr) :
    print(i)



(array(1), array(4))
(array(2), array(5))
(array(3), array(6))
