In [1]:
import numpy as np 
arr= np.random.randint(1,100, size = (10,5)) #
#print(arr)


In [3]:
# changing the shape of the array
b= arr.reshape(5,10)  # 10*5= 50 , total 50 element 
print(b)


[[ 3  9 44 69 19 55 35 36 62 20]
 [86 49 70 96  2 43 78 98 63 33]
 [48 52 48 54 42 89 78 25 19 93]
 [20 11 80 43 20 26 79  9 29 63]
 [92 85 30 21 41 19 47 56 73 26]]


In [ ]:
# flattening the array 

b.ndim
flatten = b.flatten() # 1D array row wise 
#print(flatten)

colom_flatten = np.ravel(b, order= 'F') # 1D array colom wise  , "C" -> row wise 
print(colom_flatten)


[22 89  6 95 99 27 77 18 38 10 61 76 68 44 77 88 25 82 46 77 56 97 78 89
 59 65 38 99 65  2 87 94 86 68 47 33 62 14 68 27 94 37 19 34 38 14 66 14
 63 91]


In [10]:
x= np.random.randint(1,50 , size = (2,3))
y= np.random.randint(1,50 , size =(2,3))
print(x)
print(y)

[[25 21 24]
 [44 10 21]]
[[18 33 35]
 [23 46  5]]


In [12]:
# conatenating the array

con_row = np.concatenate((x,y) , axis = 0) # row wise
print(con_row)

con_culom = np.concatenate((x,y) , axis =1 ) # culom wise
print(con_culom)

[[25 21 24]
 [44 10 21]
 [18 33 35]
 [23 46  5]]
[[25 21 24 18 33 35]
 [44 10 21 23 46  5]]


In [9]:
# concatination of array requires same number of row or culom 
# for row wise concatination number of culom should be same and vise versa

x1=np.random.randint(1,50 , size =(2,3))
x2= np.random.randint(1,50 , size =(2,4))

x3 = np.concatenate((x1,x2) , axis=1) # colum wise ( row same no error)
print(x3)
#x4= np.concatenate((x1, x2) , axis=0) # row wise , culum not same -> error


[[ 7 11 24 18 37  2 45]
 [15 29 30 47  8 12 24]]


In [13]:
# transpose  matrix

mat=np.random.randint(1, 50, size=(3,4))
print(mat)
transpose =mat.T
print(transpose , transpose.shape)

[[43 33 48 11]
 [ 5 32 20 19]
 [22 25 21 19]]
[[43  5 22]
 [33 32 25]
 [48 20 21]
 [11 19 19]] (4, 3)


In [4]:
#split araay 
arr=np.random.randint(1,10, size=(10))
print(arr)

split=np.array_split(arr, 3)
print(split)
# for equal split use split = np.split(arr, 3)  

[8 4 9 4 6 4 7 8 4 4]
[array([8, 4, 9, 4], dtype=int32), array([6, 4, 7], dtype=int32), array([8, 4, 4], dtype=int32)]


In [6]:
# arithmatic and mathematical operation on array
# for more example visit : https://numpy.org/doc/stable/reference/routines.math.html

x=np.random.randint(1,100 , size=(4))
y=np.random.randint(1,200 , size=(4))
add= x+y
div = x/y

print(x)
print(y)
print(add)
print(div)


[76 43 81 43]
[136 188 197 142]
[212 231 278 185]
[0.55882353 0.2287234  0.41116751 0.3028169 ]


In [11]:
# sin , cos , tan , log , exp
# for more example visit : https://numpy.org/doc/stable/reference/routines.math.html

sin=np.sin(x)
print(sin)

degree=np.rad2deg(x) # degree to radian 
print(degree)

base_10_log=np.log10(x)
print(base_10_log)

two_diye_koi_bar_vag_kora_jai=np.log2(x)
print(two_diye_koi_bar_vag_kora_jai)

sqrt=np.sqrt(x)
print(sqrt)

[ 0.56610764 -0.83177474 -0.62988799 -0.83177474]
[4354.47924299 2463.71851906 4640.95814056 2463.71851906]
[1.88081359 1.63346846 1.90848502 1.63346846]
[6.24792751 5.42626475 6.33985    5.42626475]
[8.71779789 6.55743852 9.         6.55743852]


In [13]:
# comparision 

a=np.array([1,2,3,4])
b=np.array([4,3,2,1])
greater_than = a > b
equal = a == b
print(equal)
print(greater_than)


# all() -> sob true kina , any() -> kono ekta true kina

print(np.all(greater_than))
print(np.any(equal))


[False False False False]
[False False  True  True]
False
False


In [16]:
# sorting 

x=np.random.randint(1,100 , size=(10))
y=x.copy()
print(y)
y.sort() # in place sorting
print(y)


[80 69 51 94 63 20 10 32 77 39]
[10 20 32 39 51 63 69 77 80 94]


In [18]:
# copy sorting 
print(x)
sorted_x= np.sort(x) # does not change x 
print(sorted_x)
print(x)

[80 69 51 94 63 20 10 32 77 39]
[10 20 32 39 51 63 69 77 80 94]
[80 69 51 94 63 20 10 32 77 39]


In [19]:
#2D sorting 
mat = np.array([[3,2,1],[6,5,4 ]])

horizontal_sort= np.sort(mat , axis=1) # row wise sorting
print(horizontal_sort)

verticla_sort=np.sort(mat , axis=0) # colom wise sorting
print(verticla_sort)


[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [6 5 4]]


In [22]:
#ndarray searching 

print(x)
index = np.where(x==63)
print(index)

index2= np.where(x>50)
print(index2)

index3=np.where(x>50 , x,0) # where condition true hole x return korbe , false hole 0 return korbe
print(index3)



[80 69 51 94 63 20 10 32 77 39]
(array([4]),)
(array([0, 1, 2, 3, 4, 8]),)
[80 69 51 94 63  0  0  0 77  0]


In [25]:
#same for 2d array 
mat=np.random.randint(1,100 , size=(3,4))
print(mat)

index=np.where(mat>50) # returns tuples of x and y axis index 
print(index)

index2 =np.where(mat>50 , mat , 0)
print(index2)

[[26  5 23 82]
 [34 93 53 27]
 [21 86 36  1]]
(array([0, 1, 1, 2]), array([3, 1, 2, 1]))
[[ 0  0  0 82]
 [ 0 93 53  0]
 [ 0 86  0  0]]


In [26]:
# counting  , min ,max 
# for more example visit : https://numpy.org/doc/stable/reference/routines.statistics.html

print(x)
count= np.count_nonzero(x>50) #
print(count)

maximum=np.max(x)
minimum = np.min(x)
maximum_index=np.argmax(x) # index of maximum value
minimum_index=np.argmin(x)

print(maximum , maximum_index)
print(minimum , minimum_index)


[80 69 51 94 63 20 10 32 77 39]
6
94 3
10 6


In [30]:
# counting 
x=np.random.randint(1,100, size=(100))
print(x)
count= np.nonzero(x==50) # returns the index of 50 
print(count)

unique=np.unique(x , return_counts=True) # unique value and their count
print(unique)


[84 28 29 59 94 55 47 79 90 23 12 37  7 44 49 53  8 20 78 28 16 71 79 25
 23 55 25 13 46 31 19 78 40  4 79 63  3 84 51 96 61 11 35 50 67 14 87 92
 72 21 11 29 70 11 49 18 87 62 48 43 14 96 75 26 11 73 28 39 88 71 75  6
 52 45 87 80 44 51 43  5 48 76 13 56 31  4 34 17 55 86 79 84  1 77 61 57
 26 21 45 36]
(array([43]),)
(array([ 1,  3,  4,  5,  6,  7,  8, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21,
       23, 25, 26, 28, 29, 31, 34, 35, 36, 37, 39, 40, 43, 44, 45, 46, 47,
       48, 49, 50, 51, 52, 53, 55, 56, 57, 59, 61, 62, 63, 67, 70, 71, 72,
       73, 75, 76, 77, 78, 79, 80, 84, 86, 87, 88, 90, 92, 94, 96],
      dtype=int32), array([1, 1, 2, 1, 1, 1, 1, 4, 1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 2,
       2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 1, 2, 1, 1, 3, 1, 1, 1,
       2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 4, 1, 3, 1, 3, 1, 1, 1, 1, 2]))


In [37]:
# statistics

# data load 
data = np.genfromtxt('students_marks.csv' , delimiter=',' , dtype=None , encoding=None) 

print(data)



[['Roll' 'Name' 'Math' 'Physics' 'English']
 ['1' 'Alice Johnson' '85' '78' '92']
 ['2' 'Bob Smith' '72' '88' '65']
 ['3' 'Carol White' '90' '95' '88']
 ['4' 'David Brown' '55' '60' '70']
 ['5' 'Emma Davis' '78' '82' '85']
 ['6' 'Frank Miller' '63' '57' '74']
 ['7' 'Grace Wilson' '91' '89' '93']
 ['8' 'Henry Moore' '48' '52' '61']
 ['9' 'Isabella Taylor' '76' '80' '79']
 ['10' 'James Anderson' '83' '75' '87']
 ['11' 'Karen Thomas' '69' '71' '68']
 ['12' 'Liam Jackson' '95' '92' '90']
 ['13' 'Mia Harris' '57' '63' '72']
 ['14' 'Noah Martin' '80' '77' '83']
 ['15' 'Olivia Garcia' '74' '85' '78']
 ['16' 'Paul Martinez' '61' '66' '59']
 ['17' 'Quinn Robinson' '88' '91' '86']
 ['18' 'Rachel Clark' '53' '49' '64']
 ['19' 'Samuel Rodriguez' '77' '73' '80']
 ['20' 'Tina Lewis' '92' '88' '94']]


In [43]:
# statistics
# for more example visit : https://numpy.org/doc/stable/reference/routines.statistics.html

math_marks = data[1:,2].astype(float) # all row and 2nd colom ( math marks)
print(math_marks)

max_mark = np.max(math_marks)
print(max_mark)

avrage_mark = np.mean(math_marks)
print(avrage_mark)

meadian = np.median(math_marks)
print(meadian)

standand_deviation = np.std(math_marks)
print(standand_deviation)

[85. 72. 90. 55. 78. 63. 91. 48. 76. 83. 69. 95. 57. 80. 74. 61. 88. 53.
 77. 92.]
95.0
74.35
76.5
13.886234190737243


In [45]:
# co -relation 

study_hours = np.array([1,2,3,4,5])
marks = np.array([40,45,64,67,77])

data = np.array([study_hours , marks])

corelation = np.corrcoef(data)
print(corelation)


[[1.         0.97513452]
 [0.97513452 1.        ]]


In [ ]:
#Linear algebra\ 
# for more example visit : https://numpy.org/doc/stable/reference/routines.linalg.html

A = np.array ([
    [1,2,3] ,
    [4,5,6],
    [7,8,9]
        ])
B= np.array([
    [7,8,9] ,
    [10,11,12]  ,
    [13,14,15] 
])

dot_product = np.dot(A,B)
print(dot_product)


# trace 
trace =np.trace(A) # sum of diagonal element
print(trace)

determinant = np.linalg.det(A)
print(determinant)

#rank 
rank = np.linalg.matrix_rank(A)
print(rank)

[[ 66  72  78]
 [156 171 186]
 [246 270 294]]
15
0.0
2
